---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipdatemodelpredict
  name: shipdatemodelpredict
  namespace: default
spec:
  ports:
  - name: model-serving
    port: 80
    targetPort: "http-server"
  selector:
    app: shipdatemodelpredict
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipdatemodelpredict
  name: shipdatemodelpredict-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipdatemodelpredict
  template:
    metadata:
      labels:
        app: shipdatemodelpredict
        version: v1
    spec:
      containers:
      - name: shipdatemodelpredict
        image: gcr.io/gcpproject1/shipdatemodelapi
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 8080
        ports:
        - name: http-server
          containerPort: 8080
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 1Gi