---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipdatepredict
  name: shipdatepredict
  namespace: default
spec:
  ports:
  - name: model-serving
    port: 80
    targetPort: "http-server"
  selector:
    app: shipdatepredict
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipdatepredict
  name: shipdatepredict-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipdatepredict
  template:
    metadata:
      labels:
        app: shipdatepredict
        version: v1
    spec:
      containers:
      - name: shipdatepredict
        image: gcr.io/gcpproject1/shipdateapi
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 8080
        ports:
        - name: http-server
          containerPort: 8080
        resources:
          limits:
            cpu: "20"
            memory: 20Gi
          requests:
            cpu: "1"
            memory: 1Gi