---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deliverydatepredict
  name: deliverydatepredict
  namespace: default
spec:
  ports:
  - name: model-serving
    port: 80
    targetPort: "http-server"
  selector:
    app: deliverydatepredict
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deliverydatepredict
  name: deliverydatepredict-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deliverydatepredict
  template:
    metadata:
      labels:
        app: deliverydatepredict
        version: v1
    spec:
      containers:
      - name: deliverydatepredict
        image: gcr.io/sodium-inverter-304318/bw-serve
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 8080
        ports:
        - name: http-server
          containerPort: 8080
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi